# Operações Matemáticas com Tensores

In [0]:
import tensorflow as tf

## Soma

In [0]:
# Constantes
const_a = tf.constant(5)
const_b = tf.constant(9)

In [3]:
print(const_a)

Tensor("Const:0", shape=(), dtype=int32)


In [0]:
# Soma
total = const_a + const_b

In [5]:
print(total)

Tensor("add:0", shape=(), dtype=int32)


In [6]:
# Sessão TensorFlow
with tf.Session() as sess:
  print('\n Soma do node1 com o node2 é: %f' % sess.run(total))


 Soma do node1 com o node2 é: 14.000000


In [7]:
# Criando os nodes no grafo computacional
node1 = tf.constant(5, dtype=tf.int32)
node2 = tf.constant(9, dtype=tf.int32)
node3 = tf.add(node1, node2)

# Cria a sessão TensorFlow
sess = tf.Session()

# Executa o grafo
print('\nA soma do node1 com o node2 é:', sess.run(node3))

# Fecha a sessão
sess.close()


A soma do node1 com o node2 é: 14


## Subtração

In [0]:
# Tensores randômicos
rand_a = tf.random_normal([3], 2.0)
rand_b = tf.random_uniform([3], 1.0, 4.0)

In [9]:
print(rand_a)

Tensor("random_normal:0", shape=(3,), dtype=float32)


In [10]:
print(rand_b)

Tensor("random_uniform:0", shape=(3,), dtype=float32)


In [0]:
# Subtração
diff = tf.subtract(rand_a, rand_b)

In [12]:
# Sessão
with tf.Session() as sess:
  print('\nTensor rand_a: ', sess.run(rand_a))
  print('\nTensor rand_b: ', sess.run(rand_b))
  print('\nSubtração entre os 2 tensores é: ', sess.run(diff))


Tensor rand_a:  [0.629421  3.6250856 1.1961491]

Tensor rand_b:  [3.902409  3.4348829 1.9384903]

Subtração entre os 2 tensores é:  [-1.2752157  1.7908037 -0.2060076]


## Divisão

In [0]:
# Divisão
node1 = tf.constant(21, dtype = tf.int32)
node2 = tf.constant(7, dtype = tf.int32)

In [14]:
div = tf.div(node1, node2)

Instructions for updating:
Deprecated in favor of operator or tf.math.divide.


In [15]:
# Sessão
with tf.Session() as sess:
  print('\nDivisão entre os 2 tensores é: ', sess.run(div))


Divisão entre os 2 tensores é:  3


## Multiplicação

In [0]:
# Criando tensores
tensor_a = tf.constant([[4., 2.]])
tensor_b = tf.constant([[3.], [7.]])

In [17]:
print(tensor_a)

Tensor("Const_6:0", shape=(1, 2), dtype=float32)


In [18]:
print(tensor_b)

Tensor("Const_7:0", shape=(2, 1), dtype=float32)


In [0]:
# Multiplicação
prod = tf.multiply(tensor_a, tensor_b)

In [20]:
# Executa a sessão
with tf.Session() as sess:
  print('\ntensor_a: \n', sess.run(tensor_a))
  print('\ntensor_b: \n', sess.run(tensor_b))
  print('\nProduto Element-wise. Entre os Tensores: \n', sess.run(prod))


tensor_a: 
 [[4. 2.]]

tensor_b: 
 [[3.]
 [7.]]

Produto Element-wise. Entre os Tensores: 
 [[12.  6.]
 [28. 14.]]


In [0]:
# Outro exemplo de Multiplicação de Matrizes
mat_a = tf.constant([[2, 3], [9, 2], [4, 5]])
mat_b = tf.constant([[6, 4, 5], [3, 7, 2]])

In [22]:
print(mat_a)

Tensor("Const_8:0", shape=(3, 2), dtype=int32)


In [23]:
print(mat_b)

Tensor("Const_9:0", shape=(2, 3), dtype=int32)


In [0]:
# Multiplicação
mat_prod = tf.matmul(mat_a, mat_b)

In [25]:
# Executa a sessão
with tf.Session() as sess:
  print('\nTensor mat_a: \n', sess.run(mat_a))
  print('\nTensor mat_b: \n', sess.run(mat_b))
  print('\nProduto Element-wise. Entre os tensores (Matrizes): \n', sess.run(mat_prod))


Tensor mat_a: 
 [[2 3]
 [9 2]
 [4 5]]

Tensor mat_b: 
 [[6 4 5]
 [3 7 2]]

Produto Element-wise. Entre os tensores (Matrizes): 
 [[21 29 16]
 [60 50 49]
 [39 51 30]]
